function llvmIdent(value) {
  return String(value).replace(/[^A-Za-z0-9_]/g, "_");
}

function fnName(rel) {
  if (rel.canonicalName) {
    return `@kfn_${llvmIdent(rel.canonicalName.replace(/^@/, ""))}`;
  }
  return `@kfn_${llvmIdent(rel.name)}`;
}

function emitExpr(expr, inputValue, ctx) {
  switch (expr.op) {
    case "RETURN_INPUT": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_return_input(%KValue ${inputValue})`);
      return out;
    }
    case "CHECK_CODE": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_guard_code(%KValue ${inputValue}, i8* ${ctx.stringConst(expr.typeId)})`);
      return out;
    }
    case "CHECK_TYPE_VAR": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_guard_type_var(%KValue ${inputValue}, i8* ${ctx.stringConst(expr.name)})`);
      return out;
    }
    case "CHECK_SHAPE": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_guard_shape(%KValue ${inputValue}, i8* ${ctx.stringConst(JSON.stringify(expr))})`);
      return out;
    }
    case "CALL": {
      const out = ctx.alloc();
      const target = ctx.functionNames[expr.target] || `@kfn_missing_${llvmIdent(expr.target)}`;
      ctx.line(`${out} = call %KOpt ${target}(%KValue ${inputValue})`);
      return out;
    }
    case "PROJECT_FIELD": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_project_field(%KValue ${inputValue}, i8* ${ctx.stringConst(JSON.stringify(expr))})`);
      return out;
    }
    case "PROJECT_VARIANT": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_project_variant(%KValue ${inputValue}, i8* ${ctx.stringConst(JSON.stringify(expr))})`);
      return out;
    }
    case "MAKE_VARIANT": {
      const out = ctx.alloc();
      ctx.line(`${out} = call %KOpt @krt_make_variant(%KValue ${inputValue}, i8* ${ctx.stringConst(expr.label)}, i8* ${ctx.stringConst(expr.exactOutputType || "")})`);
      return out;
    }
    case "MAKE_PRODUCT": {
      const fieldValues = expr.fields.map((field) => {
        const valueOpt = emitExpr(field.build, inputValue, ctx);
        return { field, valueOpt };
      });
      const out = ctx.alloc();
      ctx.line(`; make product ${expr.exactOutputType || ""} with ${fieldValues.length} field(s)`);
      ctx.line(`${out} = call %KOpt @krt_make_product_stub(i8* ${ctx.stringConst(expr.exactOutputType || "")})`);
      return out;
    }
    case "SEQ": {
      let currentInput = inputValue;
      let currentOpt = null;
      for (const step of expr.steps) {
        currentOpt = emitExpr(step, currentInput, ctx);
        currentInput = `${currentOpt}.value`;
      }
      return currentOpt;
    }
    case "TRY": {
      const out = ctx.alloc();
      ctx.line(`; try with ${expr.branches.length} branches`);
      for (const branch of expr.branches) {
        const branchOpt = emitExpr(branch, inputValue, ctx);
        ctx.line(`; branch result in ${branchOpt}`);
      }
      ctx.line(`${out} = call %KOpt @krt_fail()`);
      return out;
    }
    default:
      throw new Error(`Unsupported LLVM backend op: ${expr.op}`);
  }
}

function compileToLLVM(irModule) {
  const functionNames = Object.keys(irModule.functions).reduce((result, sourceName) => {
    result[sourceName] = fnName(irModule.functions[sourceName]);
    return result;
  }, {});

  const strings = [];
  const stringIds = new Map();
  const makeStringConst = (value) => {
    if (!stringIds.has(value)) {
      stringIds.set(value, `@.str.${stringIds.size}`);
      strings.push({ name: stringIds.get(value), value });
    }
    return stringIds.get(value);
  };

  const defs = Object.values(irModule.functions).map((rel) => {
    const lines = [];
    const ctx = {
      functionNames,
      temp: 0,
      alloc() {
        this.temp += 1;
        return `%t${this.temp}`;
      },
      line(text) {
        lines.push(`  ${text}`);
      },
      stringConst(value) {
        return makeStringConst(value);
      },
    };
    lines.push(`define %KOpt ${fnName(rel)}(%KValue %input) {`);
    const result = emitExpr(rel.body, "%input", ctx);
    lines.push(`  ret %KOpt ${result}`);
    lines.push("}");
    return lines.join("\n");
  });

  const stringDefs = strings.map(({ name, value }) => {
    const bytes = [...Buffer.from(`${value}\0`, "utf8")];
    const body = bytes.map((byte) => `i8 ${byte}`).join(", ");
    return `${name} = private constant [${bytes.length} x i8] [${body}]`;
  });

  return [
    "; Generated by k compiler LLVM backend (prototype).",
    "%KValue = type ptr",
    "%KOpt = type { i1, %KValue }",
    "",
    "declare %KOpt @krt_fail()",
    "declare %KOpt @krt_return_input(%KValue)",
    "declare %KOpt @krt_guard_code(%KValue, i8*)",
    "declare %KOpt @krt_guard_type_var(%KValue, i8*)",
    "declare %KOpt @krt_guard_shape(%KValue, i8*)",
    "declare %KOpt @krt_project_field(%KValue, i8*)",
    "declare %KOpt @krt_project_variant(%KValue, i8*)",
    "declare %KOpt @krt_make_variant(%KValue, i8*, i8*)",
    "declare %KOpt @krt_make_product_stub(i8*)",
    "",
    stringDefs.join("\n"),
    "",
    defs.join("\n\n"),
    "",
    `define %KOpt @k_entry(%KValue %input) {`,
    `  %t0 = call %KOpt ${functionNames[irModule.entryRelation]}(%KValue %input)`,
    "  ret %KOpt %t0",
    "}",
    "",
  ].join("\n");
}

export { compileToLLVM };
export default { compileToLLVM };
